trigger:
  - main
  - refs/tags/*

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

variables:
  DotNetVersion: 6.0.402
  DotNet6Source: https://aka.ms/dotnet6/nuget/index.json
  NuGetOrgSource: https://api.nuget.org/v3/index.json
  BUILD_COMMIT: $(Build.SourceVersion)
  BUILD_NUMBER: $(Build.BuildNumber)

jobs:
  - template: .ci/build.yml
    parameters:
      runCodeQL: true
      timeoutInMinutes: 240
      areaPath: 'DevDiv\VS Client - Runtime SDKs\iOS and Mac\External Bindings'
      cakeExtraArgs: '--names=$(SdksNames)'

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - template: compliance/sbom/job.v1.yml@internal-templates                 # Software Bill of Materials (SBOM): https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/ado-sbom-generator
      parameters:
        packageName: 'Xamarin Google APIs Components for iOS'
        packageFilter: '*.nupkg'
        ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
          artifactNames: ['nuget']
          dependsOn: [ 'build' ]
        ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
          artifactNames: ['nuget-signed']
          dependsOn: [ 'signing' ]
